### ISSUE TITLE
thread 'main' panicked at 'writing bytes to windows terminal console (cmd and powershell)

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl#292]
I create a file named `test.hurl` containing the sample described by https://hurl.dev/docs/samples.html#getting-data:

```hurl
GET https://example.net/news
User-Agent: Mozilla/5.0 
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```

I use hurl on my windows over cmd or powershell and i get:

```
> hurl test.hurl

thread 'main' panicked at 'writing bytes to console: Error { kind: InvalidData, message: "Windows stdio in console mode does not support writing non-UTF-8 byte sequences" }', packages\hurl\src\main.rs:448:18
stack backtrace:
   0:     0x7ff6dd3e4def - <unknown>
   1:     0x7ff6dd3fb87a - <unknown>
   2:     0x7ff6dd3dfcf8 - <unknown>
   3:     0x7ff6dd3e7846 - <unknown>
   4:     0x7ff6dd3e7329 - <unknown>
   5:     0x7ff6dd3e7ea5 - <unknown>
   6:     0x7ff6dd3e7a91 - <unknown>
   7:     0x7ff6dd3e570f - <unknown>
   8:     0x7ff6dd3e79e9 - <unknown>
   9:     0x7ff6dd448ec0 - <unknown>
  10:     0x7ff6dd448fd3 - <unknown>
  11:     0x7ff6dd189313 - <unknown>
  12:     0x7ff6dd1b6bf6 - <unknown>
  13:     0x7ff6dd1b6c8c - <unknown>
  14:     0x7ff6dd3e8406 - <unknown>
  15:     0x7ff6dd190067 - <unknown>
  16:     0x7ff6dd43fcf0 - <unknown>
  17:     0x7ff989e67c24 - BaseThreadInitThunk
  18:     0x7ff98a50d721 - RtlUserThreadStart
```

**Comment by tbolon** [comment]
Same error when requesting against `https://www.google.com`:

```
GET https://www.google.com/

HTTP/1.1 200
```

```
PS C:\...> hurl .\GoogleTests.hurl
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="fr"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/logos/doodles/2021/paulette-nardals-125th-birthday-6753651837109209.4-l.png" itemprop="image"><meta content="Il y a 125thread 'main' panicked at 'writing bytes to console: Error { kind: InvalidData, message: "Windows stdio in console mode does not support writing non-UTF-8 byte sequences" }', packages\hurl\src\main.rs:447:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fabricereix** [comment]
This is something to do with the Terminal.
It works when hurl output is redirected to a file.
We are going to look into it.
